import {
  CellStyleModule,
  CheckboxEditorModule,
  ClientSideRowModelModule,
  ColumnAutoSizeModule,
  CustomEditorModule,
  EventApiModule,
  ModuleRegistry,
  PaginationModule,
  RenderApiModule,
  RowApiModule,
  RowDragModule,
  RowStyleModule,
  SelectEditorModule,
  TextEditorModule,
  ValidationModule,
} from 'ag-grid-community'

ModuleRegistry.registerModules([
  CellStyleModule,
  CheckboxEditorModule,
  ClientSideRowModelModule,
  ColumnAutoSizeModule,
  CustomEditorModule,
  EventApiModule,
  PaginationModule,
  RenderApiModule,
  RowApiModule,
  RowDragModule,
  RowStyleModule,
  SelectEditorModule,
  TextEditorModule,
  ValidationModule,
])
